---
- name: Zabbix Repository
  yum:
    name: https://repo.zabbix.com/zabbix/5.0/rhel/8/x86_64/zabbix-release-5.0-1.el8.noarch.rpm
    state: present 

- name: Zabbix Frontend Deploy
  yum : name={{ zabbix_packages }} state=latest

- name: Zabbix Frontend Deploy | Copy zabbix.conf.php template
  template:
    src: zabbix.conf.php.j2
    dest: /etc/zabbix/web/zabbix.conf.php

- name: Ajuste do arquivo php zabbix.conf
  shell: |
          sed -i 's/\; php\_value\[date\.timezone\] \= Europe\/Riga/\php\_value\[date\.timezone\] \= America\/Sao_Paulo/g' /etc/php-fpm.d/zabbix.conf

- name: Start Frontend
  systemd:
       name=httpd
       enabled=yes
       state=started
       daemon_reload=yes

- name: Start PHP-FPM
  systemd:
       name=php-fpm
       enabled=yes
       state=started
       daemon_reload=yes

- name: Start Zabbix Agent
  systemd:
       name=zabbix-agent
       enabled=yes
       state=started
       daemon_reload=yes

- name: Firewall rule apply
  firewalld:
    port: 10050-10051/tcp
    permanent: true
    state: enabled

- name: Firewall rule apply
  firewalld:
    port: 80/tcp
    permanent: true
    state: enabled

- shell: |
        firewall-cmd --reload

        #- name: SELinux Permissive Mode 
        #  selinux:
        #    policy: targeted
        #    state: permissive
- name: Set httpd_can_network_connect flag on and keep it persistent across reboots
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
...
