---
- name : 1ยบ | Common Packages
  hosts: zabbix
  roles:
    - principal 

- name : 2ยบ | MySQL Deploy
  hosts: zabbix_mysql
  roles: 
    - zabbix-mysql
    
- name : 3ยบ | Zabbix Server
  hosts: zabbix_server
  roles:
    - zabbix-server

- name : 4ยบ - Zabbix Frontend
  hosts: zabbix_frontend
  roles:
    - zabbix-frontend
...
